// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GooseDBVersion string
	Jets           string
	Languages      string
	PilotLanguages string
	Pilots         string
}{
	GooseDBVersion: "goose_db_version",
	Jets:           "jets",
	Languages:      "languages",
	PilotLanguages: "pilot_languages",
	Pilots:         "pilots",
}
